CREATE TABLE product (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    price DECIMAL(19, 2) NOT NULL,
    category_id BIGINT,
    brand_id BIGINT,
    deleted_at TIMESTAMP,
    created_by VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(255) NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_product_category FOREIGN KEY (category_id) REFERENCES product_category (id),
    CONSTRAINT fk_product_brand FOREIGN KEY (brand_id) REFERENCES brand (id)
);

CREATE INDEX idx_product_category_id ON product (category_id);
CREATE INDEX idx_product_brand_id ON product (brand_id);
CREATE INDEX idx_product_price ON product (price);

CREATE INDEX idx_product_brand_id_deleted_at ON product (brand_id, deleted_at);
CREATE INDEX idx_product_category_deleted_at ON product (category_id, deleted_at);
